name: Main test

on:
  schedule:
    - cron: '23 * * * *'
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo "seting up..."
  
