name: Trigger Action on a CRON Schedule

on:
  schedule:
    - cron: '45 * * * *'
    
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
