name: Run cron job

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  build:
    name: Shell script syntax test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate shell script syntax
        run: |
          sh -n bootstrap.sh
          echo "shell script check finished !"
