name: Run CRON Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
    
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
