name: Setup

on: 
  #pull_request:
  #workflow_dispatch:
  schedule:
    - cron: '53 * * * *'
jobs:
  build:
    name: setup test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "testing"
